baseURL = "https://rubhl.github.io/"
languageCode = "en-us"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    name = "example.org"
    title = "Sada Theme"
    author = "Darshan Baral"
    description = "Sobre mí"
    copyright = "Custom copyright message"
    theme = "light" # `dark` or `light`
    useResources = false

    # Profile section
    [params.profile]
        name = "Ruben.H"
        photo = "images/mono.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "#"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/RubHL"
        title = "GitHub"
			
       # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Masters in Degree 1"
        college = "University Number 1"
        dates = "2016 - 2018"
        thesis_title = "Title of the dissertation"
        thesis_link = "#"

        [[params.education.list]]
        degree = "Bachelors in Degree 2"
        college = "University Number 2"
        dates = "2010 - 2014"

    # Languages section
    [params.language]
        title = "Idiomas"

        [[params.language.list]]
        language = "Español"
        level = "Nativo"
				
        [[params.language.list]]
        language = "Inglés"
        level = "Medio"


    [params.aboutme]
        description = "Estudiante técnico superior en desarrollo web"

    # Experiences section
    [params.experiences]
        title = "Experiences"

        [[params.jobs.list]]
        position = "Job Number 1"
        dates = "2018 - *Present*"
		link = "#"
        company = "Company name 1"

        [[params.jobs.list]]
        position = "Job Number 2"
        dates = "2016 - 2018"
		link = "#"
        company = "Company name 2"
        details = "Brief description of the `work` done. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

     # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "Awesome Project 1"
        url = "#"
        description = "Description of the *awesome* project 1"
		
		[[params.projects.list]]
        title = "Awesome Project 2"
        url = "#"
        description = "Description of the **awesome** project 2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."


    # Skills section
    [params.skills]
        title = "Habilidades"

        [[params.skills.list]]
        skill = "html/css"
        skillrating = 95 # out of 100
                
        [[params.skills.list]]
        skill = "Javascript"
        skillrating = 90
		
        [[params.skills.list]]
        skill = "Hugo framework"
        skillrating = 80